# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Example

  pod 'THFlexiblePageController', :path => '../../../'

  target 'iOS ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
